services:
  bncserver-mysql:
    image: mysql
    container_name: bncserver-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306